name: spacex_graphql
description: A new Flutter package project.
# homepage: https://www.example.com

version: 1.0.0

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  graphql: ^5.1.2-beta.4
  graphql_flutter: ^5.1.1-beta.4

dev_dependencies:
  build_runner: ^2.3.0
  graphql_codegen: ^0.11.1

  very_good_analysis: ^3.1.0
  test: 1.21.6

